### ISSUE TITLE
Roadmap to complete PDS

### ISSUE THREAD

**Issue by snarfed** [snarfed/arroba#2]
Moved here from https://github.com/snarfed/bridgy-fed/issues/381. Bluesky team still hasn't launched federation yet, so this is somewhat speculation, but [their docs](https://atproto.com/guides/data-repos) and [blog posts](https://blueskyweb.xyz/blog/5-5-2023-federation-architecture) and [discussions](https://github.com/bluesky-social/atproto/discussions) and comments in chat have painted a pretty complete picture. Here's what we think we still need:

- [x] XRPC: https://lexrpc.readthedocs.io/, https://github.com/snarfed/lexrpc
  - [ ] Validate data against lexicon schemas (optional)
- [x] Data conversion to/from `app.bsky` lexicons in granary: 
- ~~[x] Bridgy Fed serves most [`app.bsky` read XRPCs](https://atproto.com/lexicons/app-bsky-feed), eg https://fed.brid.gy/xrpc/app.bsky.feed.getAuthorFeed?author=snarfed.org~~
- [x] Federation
  - [x] MST
  - [x] signed commit chain
  - ~~[ ] blob serving~~
  - [x] remaining `com.atproto.sync` methods
  - [x] guarantee that commit chains we serve are immutable ([except for rebases](https://github.com/bluesky-social/atproto/discussions/889#discussioncomment-5724576))
  - [x] DID resolution
  - ~~[ ] ingest/sync other PDSes' repos~~
  - ~~[ ] did:web serving~~

**Comment by snarfed** [comment]
Done! Woo!
